In [72]:
# multiple linear Regression
# jyare 'y' multiple x per dependent hoy to multiple Linear Regression no use thay...
# y= m1x1 + m2x2 + m3x3 + m4x4 + c


# step-1
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
data=pd.read_csv("Car data.csv")
df=pd.DataFrame(data)
df.head()

# step-2 check null value
df.isna().sum()


# step-3 data convert numeric format
df["age"]=2026-df["Year"]
df
df.drop(columns="Year",inplace=True)
df.drop(columns="Car_Name",inplace=True)
df

df=pd.get_dummies(data=df,drop_first=True)
df


# step-4 defind x,y
y=df["Selling_Price"]
x=df[['Present_Price', 'Kms_Driven', 'Owner', 'age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual']]

In [73]:
df.columns

Index(['Selling_Price', 'Present_Price', 'Kms_Driven', 'Owner', 'age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual'],
      dtype='object')

In [74]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [75]:
print(x_train.shape)#2d
print(x_test.shape)#2d
print(y_train.shape)
print(y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)

In [76]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [77]:
m=lr.coef_
m

array([ 4.29152503e-01, -6.15725866e-06, -9.03759824e-01, -3.53801365e-01,
        2.53327258e+00,  7.38464226e-01, -1.19059291e+00, -1.63902155e+00])

In [78]:
c=lr.intercept_
c

np.float64(6.848642647119785)

In [79]:
# age=8
# petrol
# menual
# 45000 km
# owner 0
# present price 8.5 lakh
# sellar type=indiv

In [80]:
i20_price=lr.predict([[8,45000,0,8,0,1,1,1]])
i20_price

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([5.08322487])

In [81]:
y_pred=lr.predict(x_test)
print("MSE:",mean_squared_error(y_pred,y_test))

MSE: 3.478803970637871

In [92]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
data=pd.read_csv("winequality.csv")
df=pd.DataFrame(data)
df.head()

# step-2 check null value
df.isna().sum()
df
df.drop(columns="Id",inplace=True)
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5

In [97]:
x=df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]
y=df["quality"]

In [98]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)#2d
print(x_test.shape)#2d
print(y_train.shape)
print(y_test.shape)

(914, 11)
(229, 11)
(914,)
(229,)

In [100]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [101]:
m=lr.coef_
m

array([ 5.13430654e-02, -1.33625691e+00, -3.39100758e-01,  4.12143173e-03,
       -1.80653035e+00,  1.88076181e-03, -2.28305818e-03, -3.06532562e+01,
       -2.49236344e-01,  9.73040097e-01,  2.66586068e-01])

In [102]:
c=lr.intercept_
c

np.float64(34.209805578378685)

In [106]:
wine=lr.predict([[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]])
wine

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([5.80087585])

In [110]:
y_pred=lr.predict(x_test)
# print(y_pred)
print("MSE:",mean_squared_error(y_pred,y_test))

MSE: 0.38003245026277577

In [127]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
data=pd.read_csv("RealEstate.csv")
df=pd.DataFrame(data)
df.head()

# step-2 check null value
df.isna().sum()

# df.drop(columns="Id",inplace=True)
df.drop(columns="No",inplace=True)
df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [128]:
x=df[['X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']]
y=df["Y house price of unit area"]

In [129]:
df.columns
df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [134]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=110)
print(x_train.shape)#2d
print(x_test.shape)#2d
print(y_train.shape)
print(y_test.shape)

(289, 6)
(125, 6)
(289,)
(125,)

In [135]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [136]:
m=lr.coef_
m

array([ 6.84308941e+00, -2.25466590e-01, -5.18046265e-03,  1.12369103e+00,
        1.87739728e+02, -4.29300312e+01])

In [137]:
c=lr.intercept_
c

np.float64(-13203.674300629997)

In [139]:
y_pred=lr.predict(x_test)
# print(y_pred)
print("MSE:",mean_squared_error(y_pred,y_test))

MSE: 77.14802598253598

In [140]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np



df = pd.read_csv("RealEstate.csv")

# print(df.head(5))

# print(df.columns)


x = df[['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']]

y = df['Y house price of unit area']

# print(df.isna())
# print(df.isna().sum())




from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 110)



from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(x_train, y_train)



from sklearn.metrics import mean_squared_error

y_pred = lr.predict(x_test)
print(y_pred)
print('MSE:', mean_squared_error(y_test, y_pred))
# print(y_pred)

[40.05433752 32.567899   29.82570991 44.5953719  39.98292821 44.330833
 37.62555729 51.18220121 37.10312284 38.67128726 36.47724061 31.66193514
 43.04394193 16.64151632 36.57102889 31.26087    39.5868985  41.936409
 46.46073447 42.69461105 40.51840431 53.32366115 40.72999166 36.66741707
 46.85772644 42.76413278 47.22504134 40.55764483 42.59694952 50.88066126
 44.7822605  41.08878953 35.42129907 42.96667011 13.94916617 29.99936955
  0.31341832 39.5836877  47.94733623 34.02528984 40.26668668 49.70695505
 36.72385967 35.3616091  29.62339934 45.8485651  42.41267711 37.86546064
 31.58211091 47.50187613 35.04027072 45.18399673 45.97460622 47.32854158
 54.20538585 15.20882594 43.76374676 44.7740197  37.67420893 39.33262496
 44.25710176 44.31348102 47.8451065  38.42525146 41.06494215 19.65156766
 47.9931899  43.89289898 37.98581356 43.78917237 42.39110913 42.56204498
 44.75925014 32.35791343 46.86942957 38.95700863 40.93161655 43.93269845
 34.23974688 25.61210624 16.26161646 45.63531221 42.04326458 10.83741422
 31.66184693 49.1100805  47.3822276  13.59628219 46.04451043 44.79628782
 34.7496268  35.37799124 31.46520123 45.55802041 42.00635968 42.57448178
 14.68055207 43.69630093 27.66678871 43.08068536 27.67865624 35.20975488
 45.88437543 50.34830481 42.87262729 44.58172042 49.62631177 32.14302096
 31.88929491 38.364619   44.54642216 25.52626948 46.17763813 37.44442408
 14.6970433  44.21917103  9.21970138 37.21929092 38.95177352 47.42908684
 39.48237161 32.16290109 46.97438744 47.0426921  53.13883137]
MSE: 77.2178303091099